# -*- coding: utf-8 -*-
"""ANN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s5cldM9WKkB20jVW31tSjdei-z0rlPhm

Load Data from Sklearn
"""

from sklearn.datasets import load_breast_cancer

breast_cancer_data = load_breast_cancer()

breast_cancer_data

"""Converting data Into Data Frame & EDA"""

import pandas as pd
data=pd.DataFrame(breast_cancer_data.data,columns=breast_cancer_data.feature_names)
data['target'] = breast_cancer_data.target

data.head()

data.info()

data.shape

data.isna().sum()

data.describe()

"""check for imbalanced class"""

target_counts = data['target'].value_counts()
target_names = breast_cancer_data.target_names
malignant_count = target_counts[0]
benign_count = target_counts[1]

print(f"Count of {target_names[0]} (target=0): {malignant_count}")
print(f"Count of {target_names[1]} (target=1): {benign_count}")

"""Split the Data into X & Y"""

x=data.drop('target', axis=1)
y=data['target']

"""Train_test_Split"""

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.01, random_state=42)

"""Standardization"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_scaled_train=scaler.fit_transform(x_train)
x_scaled_test=scaler.fit_transform(x_test)

"""ANN model"""

from tensorflow import keras

model=keras.Sequential([
    keras.layers.Flatten(input_shape=(30,)),
    keras.layers.Dense(20,activation='relu'),
    keras.layers.Dense(2,activation='sigmoid')
])

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

history=model.fit(x_scaled_train,y_train,validation_split=0.2,epochs=15)

test_loss, test_acc = model.evaluate(x_scaled_test, y_test)
print(f'Test accuracy: {test_acc}')
print(f'Test loss: {test_loss}')

"""Model Visualization


"""

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.title('Model Accuracy over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)
plt.show()

y_pred=model.predict(x_scaled_test)

"""Sample Prediction"""

import numpy as np

y_pred1=np.argmax(y_pred,axis=1)

y_pred1

"""Load CIFAR-10 dataset

"""

from keras.datasets import cifar10

(x_train, y_train), (x_test, y_test) = cifar10.load_data()
print("CIFAR-10 dataset loaded successfully.")
print(f"x_train shape: {x_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"x_test shape: {x_test.shape}")
print(f"y_test shape: {y_test.shape}")

x_train = x_train / 255.0
x_test = x_test / 255.0

print("x_train normalized minimum value:", x_train.min())
print("x_train normalized maximum value:", x_train.max())
print("x_test normalized minimum value:", x_test.min())
print("x_test normalized maximum value:", x_test.max())

x_train = x_train.reshape(-1, 32*32*3)
x_test = x_test.reshape(-1, 32*32*3)

print(f"x_train shape after flattening: {x_train.shape}")
print(f"x_test shape after flattening: {x_test.shape}")

from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Dense(128, activation='relu', input_shape=(x_train.shape[1],)),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

print("ANN model defined successfully.")
model.summary()

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

history = model.fit(x_train, y_train, epochs=10, validation_data=(x_test, y_test))